name: habit_wallet_lite
description: "Offline-first personal finance mini app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Local Database (Offline-first)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.2

  # Timezone (for notifications)
  timezone: ^0.9.4

  # Immutable Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Charts
  fl_chart: ^0.66.2

  # Secure Storage (Auth Stub)
  flutter_secure_storage: ^9.2.2

  # Localization (i18n)
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter

  # Notifications
  flutter_local_notifications: ^17.2.2

  # File picker
  file_picker: ^10.3.8

  # Local preferences
  shared_preferences: ^2.2.3

  # App icons
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/mock/

flutter_icons:
  android: true
  ios: true
  image_path: assets/img/logo.png
  min_sdk_android: 21
